FROM debian:11-slim

RUN apt-get update && \
    apt-get install -y lib32z1  && \
    apt-get install -y redis-server && \
    apt-get install gzip && \
    apt-get install -y python && \
    apt-get clean

ADD packages/j2sdk-1_4_2_19-linux-i586.bin /
RUN chmod +x j2sdk-1_4_2_19-linux-i586.bin
RUN (echo yes) | sh j2sdk-1_4_2_19-linux-i586.bin

ADD packages/enhydra5.1 /usr/local/enhydra5.1
ADD packages/JOnAS-4.3.4 /usr/local/JOnAS-4.3.4
ADD packages/jython-2.0 /usr/local/jython-2.0
ADD packages/lib.2 /usr/local/lib.2
ADD packages/lib-apps /usr/local/lib-apps


ADD packages/apache-ant-1.5.3-1 /usr/local/apache-ant-1.5.3-1
RUN ln -s /usr/local/apache-ant-1.5.3-1 /usr/local/ant

ENV JONAS_ROOT /usr/local/JOnAS-4.3.4
ENV LIB_JARS /usr/local/lib.2
ENV JAVA_APPS /usr/local/lib-apps
ENV ENHYDRA_HOME /usr/local/enhydra5.1
ENV JYTHON_HOME /usr/local/jython-2.0

ENV ANT_HOME /usr/local/ant
ENV PATH $ANT_HOME/bin:$PATH

ENV JAVA_HOME /j2sdk1.4.2_19
ENV PATH $PATH:$JAVA_HOME/bin

EXPOSE 6379

CMD ["redis-server", "--protected-mode no"]
